import {cpSync,rmSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const checkout=resolve(process.argv[2]||'');
if(!process.argv[2])throw Error('Pass the isolated publication checkout');
const baseline='2f7c031c517ce9b4d04b68d7cbb584c2811c32a6';
const git=(...args)=>execFileSync('git',args,{cwd:checkout,encoding:'utf8'}).trim();
if(git('rev-parse','HEAD')!==baseline||git('rev-parse','origin/main')!==baseline)throw Error('Public baseline changed; inspect and rebase before publication');
if(git('status','--porcelain'))throw Error('Publication checkout must be clean');
const source=resolve('out/varathans25/premium-preview');
if(!existsSync(resolve(source,'release.json')))throw Error('Build and audit before publishing');
const target=resolve(checkout,'varathans25/premium-preview');
if(!target.startsWith(checkout+'/varathans25/'))throw Error('Output boundary');
rmSync(target,{recursive:true,force:true});mkdirSync(target,{recursive:true});cpSync(source,target,{recursive:true});
const changed=git('diff','--name-only',baseline).split('\n').filter(Boolean);
if(changed.some(file=>!file.startsWith('varathans25/premium-preview/')))throw Error('Unrelated public file changed');
const untracked=git('ls-files','--others','--exclude-standard').split('\n').filter(Boolean);
if(untracked.some(file=>!file.startsWith('varathans25/premium-preview/')))throw Error('Unrelated public file added');
console.log(`Prepared only varathans25/premium-preview/ on ${baseline}; preserved unrelated routes and files.`);
