export const locales = ['de', 'fr', 'en'] as const;
export type Locale = typeof locales[number];
export const base = '/varathans25/premium-preview';
export const link = (locale: Locale, route = '') => `${base}/${locale}/${route ? `${route}/` : ''}`;
const de = {
  title: 'Zeit für das Wesentliche.', store: 'General Store', club: 'Premium Cigar Club · 18+',
  catalogue: 'Kollektion', account: 'Mein Konto', login: 'Anmelden', basket: 'Warenkorb',
  language: 'Sprache wählen', menu: 'Menü', close: 'Schliessen', skip: 'Zum Inhalt',
  pause: 'Film pausieren', play: 'Film abspielen', still: 'Standbild',
  storeTitle: 'Ein Moment.\nEine Tasse Tee.', storeText: 'Die Teekollektion von Varathans25.',
  teaTitle: 'Fünf Tees.\nIhre Auswahl.', teaText: 'Entdecken Sie die fünf Teedosen unserer Kollektion.',
  pourTitle: 'Die Kunst des Tees', pourText: 'Ein stiller Moment vor der Kollektion.',
  spiceTitle: 'Gewürze.\nIn ihrer ganzen Vielfalt.', spiceText: 'Ein Blick in die Welt der Gewürze.',
  curryTitle: 'Varathans25\nCurry.', curryText: 'Gelber Curry Kokos. Entdecken Sie unser Curry und die verfügbaren Produktinformationen.',
  restaurantTitle: 'Ein Abend\nüber Sursee.', restaurantText: 'Rooftop-Bar und Restaurant Varathans25.', restaurant: 'Restaurant entdecken',
  tea: 'Tee', curry: 'Curry', all: 'Alle Produkte', details: 'Produktinformationen',
  pending: 'Produktangaben werden bestätigt.', price: 'Preis noch nicht bestätigt', stock: 'Verfügbarkeit noch nicht bestätigt',
  weight: 'Packungsgrösse', quantity: 'Menge', plus: 'Menge erhöhen', minus: 'Menge verringern',
  add: 'Auswahl speichern', added: 'Auswahl gespeichert', remove: 'Entfernen', empty: 'Ihr Warenkorb ist leer.',
  selection: 'Ihre Auswahl', basketNote: 'Ihre Auswahl wird nur in diesem Browser gespeichert. Preise und Verfügbarkeit sind noch nicht bestätigt. Bestellungen und Zahlungen sind hier nicht verfügbar.',
  browserStorage: 'Die Auswahl konnte nicht dauerhaft gespeichert werden.', continue: 'Kollektion entdecken',
  clubTitle: 'Willkommen\nim Club.', clubText: 'Ihr persönlicher Zugang zu Varathans25.',
  member: 'Mitgliederzugang', membership: 'Mitgliedschaft', recovery: 'Passwort zurücksetzen',
  serviceTitle: 'Ihr persönlicher Zugang.', service: 'Die Online-Anmeldung ist derzeit nicht verfügbar. Kontodaten, Mitgliedschaften und Verifizierungen benötigen einen verbundenen Kontoservice.',
  serviceShort: 'Anmeldung und Kontoverwaltung sind derzeit nicht verfügbar.',
  memberText: 'Informationen zu Ihrer Mitgliedschaft und Ihrem Verifizierungsstatus stehen über den verbundenen Kontoservice zur Verfügung.',
  contact: 'Varathans25 kontaktieren', back: 'Zurück zur Kollektion',
  privacy: 'Datenschutz', privacyText: 'Diese öffentliche Vorschau erfasst keine Kontodaten und verarbeitet keine Bestellungen oder Zahlungen. Die optionale Produktauswahl wird lokal in Ihrem Browser gespeichert. Sie können sie im Warenkorb löschen.',
  clear: 'Auswahl löschen', legal: 'Hinweise', legalText: 'Produktpreise, Verfügbarkeit und noch nicht bestätigte Produktangaben werden hier nicht als Verkaufsangebot dargestellt. Die öffentliche Vorschau bietet keine Anmeldung, Bestellung oder Zahlung an.',
  notice: 'Öffentliche Vorschau · Bestellungen und Zahlungen nicht verfügbar',
  ingredients: 'Zutaten', allergens: 'Allergene', preparation: 'Zubereitung',
  facts: 'Produktangaben', noFacts: 'Zusammensetzung, Herkunft und Packungsgrösse werden noch bestätigt.',
  filmNote: 'VARATHANS25 · SURSEE', destinations: 'Bereich wählen', navigation: 'Hauptnavigation', footer: 'Weitere Seiten',
};
type Copy = typeof de;
export const copy: Record<Locale, Copy> = {
  de,
  fr: {
    title: 'Le temps de l’essentiel.', store: 'Boutique générale', club: 'Premium Cigar Club · 18+',
    catalogue: 'Collection', account: 'Mon compte', login: 'Connexion', basket: 'Panier', language: 'Choisir la langue',
    menu: 'Menu', close: 'Fermer', skip: 'Aller au contenu', pause: 'Mettre le film en pause', play: 'Lire le film', still: 'Image fixe',
    storeTitle: 'Un moment.\nUne tasse de thé.', storeText: 'La collection de thés Varathans25.', teaTitle: 'Cinq thés.\nVotre sélection.',
    teaText: 'Découvrez les cinq boîtes de notre collection de thés.', pourTitle: 'L’art du thé', pourText: 'Un instant de calme avant la collection.',
    spiceTitle: 'Les épices.\nDans toute leur diversité.', spiceText: 'Un regard sur le monde des épices.', curryTitle: 'Le curry\nVarathans25.',
    curryText: 'Gelber Curry Kokos. Découvrez notre curry et les informations produit disponibles.', restaurantTitle: 'Une soirée\nau-dessus de Sursee.',
    restaurantText: 'Rooftop-bar et restaurant Varathans25.', restaurant: 'Découvrir le restaurant', tea: 'Thés', curry: 'Curry', all: 'Tous les produits', details: 'Informations produit',
    pending: 'Informations produit en cours de confirmation.', price: 'Prix non confirmé', stock: 'Disponibilité non confirmée', weight: 'Format', quantity: 'Quantité',
    plus: 'Augmenter la quantité', minus: 'Diminuer la quantité', add: 'Enregistrer la sélection', added: 'Sélection enregistrée', remove: 'Retirer', empty: 'Votre panier est vide.',
    selection: 'Votre sélection', basketNote: 'Votre sélection est enregistrée uniquement dans ce navigateur. Les prix et la disponibilité restent à confirmer. Les commandes et paiements ne sont pas disponibles ici.',
    browserStorage: 'La sélection n’a pas pu être enregistrée durablement.', continue: 'Découvrir la collection', clubTitle: 'Bienvenue\nau club.', clubText: 'Votre accès personnel à Varathans25.',
    member: 'Accès membre', membership: 'Adhésion', recovery: 'Réinitialiser le mot de passe', serviceTitle: 'Votre accès personnel.',
    service: 'La connexion en ligne est actuellement indisponible. Les comptes, adhésions et vérifications nécessitent un service de compte connecté.',
    serviceShort: 'La connexion et la gestion du compte sont actuellement indisponibles.', memberText: 'Les informations d’adhésion et de vérification sont accessibles via le service de compte connecté.',
    contact: 'Contacter Varathans25', back: 'Retour à la collection', privacy: 'Confidentialité', privacyText: 'Cet aperçu public ne recueille aucune donnée de compte et ne traite aucune commande ni aucun paiement. La sélection facultative est enregistrée dans votre navigateur et peut être supprimée dans le panier.',
    clear: 'Effacer la sélection', legal: 'Informations', legalText: 'Les prix, la disponibilité et les informations produit non confirmées ne constituent pas une offre de vente. Cet aperçu ne propose aucune connexion, commande ou paiement.',
    notice: 'Aperçu public · Commandes et paiements indisponibles', ingredients: 'Ingrédients', allergens: 'Allergènes', preparation: 'Préparation', facts: 'Informations produit', noFacts: 'La composition, l’origine et le format sont en cours de confirmation.',
    filmNote: 'VARATHANS25 · SURSEE', destinations: 'Choisir une destination', navigation: 'Navigation principale', footer: 'Autres pages',
  },
  en: {
    title: 'Time for what matters.', store: 'General Store', club: 'Premium Cigar Club · 18+', catalogue: 'Collection', account: 'My account', login: 'Sign in', basket: 'Basket', language: 'Choose language',
    menu: 'Menu', close: 'Close', skip: 'Skip to content', pause: 'Pause film', play: 'Play film', still: 'Still image', storeTitle: 'A moment.\nA cup of tea.', storeText: 'The Varathans25 tea collection.',
    teaTitle: 'Five teas.\nYour selection.', teaText: 'Discover the five tins in our tea collection.', pourTitle: 'The art of tea', pourText: 'A quiet moment before the collection.',
    spiceTitle: 'Spices.\nIn all their variety.', spiceText: 'A look into the world of spices.', curryTitle: 'Varathans25\nCurry.', curryText: 'Gelber Curry Kokos. Explore our curry and its available product information.',
    restaurantTitle: 'An evening\nabove Sursee.', restaurantText: 'Varathans25 rooftop bar and restaurant.', restaurant: 'Discover the restaurant', tea: 'Tea', curry: 'Curry', all: 'All products', details: 'Product information',
    pending: 'Product information is being confirmed.', price: 'Price awaiting confirmation', stock: 'Availability awaiting confirmation', weight: 'Pack size', quantity: 'Quantity', plus: 'Increase quantity', minus: 'Decrease quantity',
    add: 'Save selection', added: 'Selection saved', remove: 'Remove', empty: 'Your basket is empty.', selection: 'Your selection', basketNote: 'Your selection is saved only in this browser. Prices and availability are awaiting confirmation. Orders and payments are unavailable here.',
    browserStorage: 'Your selection could not be saved permanently.', continue: 'Explore the collection', clubTitle: 'Welcome\nto the club.', clubText: 'Your personal entrance to Varathans25.', member: 'Member access', membership: 'Membership', recovery: 'Reset password',
    serviceTitle: 'Your personal access.', service: 'Online sign-in is currently unavailable. Accounts, memberships and verification require a connected account service.', serviceShort: 'Sign-in and account management are currently unavailable.', memberText: 'Membership and verification information is available through the connected account service.',
    contact: 'Contact Varathans25', back: 'Back to the collection', privacy: 'Privacy', privacyText: 'This public preview collects no account details and processes no orders or payments. Optional product selections are saved in your browser and can be cleared in the basket.', clear: 'Clear selection', legal: 'Information',
    legalText: 'Prices, availability and unconfirmed product details are not presented as a sales offer. This public preview provides no sign-in, ordering or payment service.', notice: 'Public preview · Orders and payments unavailable', ingredients: 'Ingredients', allergens: 'Allergens', preparation: 'Preparation', facts: 'Product information', noFacts: 'Composition, origin and pack size are awaiting confirmation.',
    filmNote: 'VARATHANS25 · SURSEE', destinations: 'Choose a destination', navigation: 'Main navigation', footer: 'More pages',
  },
};
