begin;
select plan(25);
select is((select count(*)::integer from pg_tables t join pg_class c on c.relname=t.tablename join pg_namespace n on n.oid=c.relnamespace and n.nspname=t.schemaname where t.schemaname='public' and t.tablename like 'v25_%' and not c.relrowsecurity),0,'RLS enabled on every exposed platform table');
select ok(not has_table_privilege('anon','public.v25_members','SELECT'),'anonymous member table denied');
select ok(not has_table_privilege('authenticated','public.v25_members','INSERT'),'member self-promotion through INSERT denied');
select ok(not has_table_privilege('authenticated','public.v25_payments','UPDATE'),'payment direct writes denied');
select ok(not has_table_privilege('authenticated','public.v25_memberships','UPDATE'),'membership direct writes denied');
select ok(not has_table_privilege('authenticated','public.v25_staff_roles','INSERT'),'staff role escalation denied');
select ok(not has_function_privilege('anon','public.v25_platform_action(text,jsonb,uuid)','EXECUTE'),'anonymous RPC mutations denied');
select ok(not has_function_privilege('anon','public.v25_guest_create_order(jsonb,uuid)','EXECUTE'),'guest order RPC denies anonymous bypass');
select ok(not has_function_privilege('authenticated','public.v25_guest_create_order(jsonb,uuid)','EXECUTE'),'guest order RPC denies authenticated browser bypass');
select ok(has_function_privilege('service_role','public.v25_guest_create_order(jsonb,uuid)','EXECUTE'),'guest order RPC requires the server service role');
select ok(not has_function_privilege('authenticated','public.v25_platform_webhook(uuid,text,integer,text,text)','EXECUTE'),'webhook RPC requires service role');
select ok(not has_function_privilege('authenticated','public.v25_platform_rate_limit(text,integer)','EXECUTE'),'rate limiter cannot be reset by browser');
select ok(not has_function_privilege('service_role','public.v25_create_order(jsonb)','EXECUTE'),'legacy checkout inaccessible even to service role');
select ok(not has_function_privilege('authenticated','v25_private.payment_apply(uuid,text,integer,text,text,text)','EXECUTE'),'private payment function inaccessible');
select ok(not has_table_privilege('authenticated','v25_private.platform_runtime','UPDATE'),'runtime mode cannot be changed by member');
select ok(not has_table_privilege('anon','v25_private.platform_idempotency','SELECT'),'idempotency data private');
select is((select fee_rappen from public.v25_membership_plans where id='gold-monthly'),6900,'monthly Gold fee integer rappen');
select is((select fee_rappen from public.v25_membership_plans where id='gold-yearly'),50000,'annual Gold fee integer rappen');
select is((select standard_rappen from public.v25_delivery_methods where id='standard-ch'),1000,'Silver standard delivery CHF 10');
select is((select threshold_rappen from public.v25_delivery_methods where id='standard-ch'),10000,'inclusive free delivery threshold CHF 100');
select ok((select not payment_enabled and not tobacco_checkout_enabled from public.v25_store_settings),'legacy live sales flags disabled');
select throws_ok($$update public.v25_store_settings set bundle_discount_bps=500$$,'23514',null,'legacy tobacco discount cannot be enabled');
insert into public.v25_audit_events(actor,action,entity,entity_id) values(null,'TEST','test','test');
select throws_ok($$delete from public.v25_audit_events where entity='test'$$,'42501','Immutable event history','audit history immutable');
update v25_private.platform_runtime set local_test=false;
select throws_ok($$select v25_private.local_write()$$,'42501','Writes disabled','hosted/default runtime denies writes');
select is((select count(*)::integer from pg_proc p join pg_namespace n on p.pronamespace=n.oid where n.nspname='v25_private' and p.prosecdef and not coalesce(p.proconfig,'{}') @> array['search_path=""']),0,'security definer functions pin search_path');
select * from finish();
rollback;
