begin;
select plan(13);
select ok(not has_table_privilege('authenticated','public.v25_member_verifications','UPDATE'),'users cannot update verification');
select ok(not has_table_privilege('authenticated','public.v25_members','UPDATE'),'users cannot update protected profile fields');
select ok(not has_table_privilege('authenticated','public.v25_profiles','INSERT'),'users cannot grant admin role');
select ok(not has_function_privilege('authenticated','v25_private.platform_action_legacy(text,jsonb,uuid)','EXECUTE'),'legacy self approval removed');
select ok(not has_function_privilege('service_role','v25_private.platform_action_legacy(text,jsonb,uuid)','EXECUTE'),'service cannot bypass action wrapper');
select ok(not has_function_privilege('anon','public.v25_verification_submit(text)','EXECUTE'),'anonymous verification submission rejected');
select ok(not has_function_privilege('anon','public.v25_verification_review(uuid,text,text,integer)','EXECUTE'),'anonymous approval rejected');
select throws_ok($$select public.v25_platform_action('test_verification','{"status":"verified"}')$$,'42501','Authorized verification workflow required','old local approval shortcut rejected');
select throws_ok($$select public.v25_verification_review(gen_random_uuid(),'approve','age_confirmed',1)$$,'42501','Independent authorized administrator required','review validates administrator');
select ok(not has_table_privilege('authenticated','public.v25_audit_events','UPDATE'),'audit cannot be edited');
select is((select count(*)::integer from storage.buckets where public),0,'no public storage buckets');
insert into auth.users(id,email,email_confirmed_at) values('b0180000-0000-4000-8000-000000000001','session-test@v25.local.test',now());
insert into auth.sessions(id,user_id,created_at,updated_at,refreshed_at) values('b0180000-0000-4000-8000-000000000002','b0180000-0000-4000-8000-000000000001',now()-interval '9 hours',now(),now());
select set_config('request.jwt.claims','{"sub":"b0180000-0000-4000-8000-000000000001","session_id":"b0180000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select ok(not v25_private.session_valid(),'absolute expiry rejects a recently refreshed nine-hour-old session');
update auth.sessions set created_at=now(),refreshed_at=now() where id='b0180000-0000-4000-8000-000000000002';
select ok(v25_private.session_valid(),'fresh authenticated session remains valid');
select * from finish();rollback;
